# frozen_string_literal: true

require_relative "stat_power/version"
require_relative "stat_power/result"
require_relative "stat_power/power_result"
require_relative "stat_power/unequal_power_result"
require_relative "stat_power/anova_result"
require_relative "stat_power/f2_result"
require_relative "stat_power/chi_square_result"
require_relative "stat_power/errors"
require_relative "stat_power/special_functions/beta"
require_relative "stat_power/special_functions/gamma"
require_relative "stat_power/integration/adaptive_simpson"
require_relative "stat_power/distributions/normal"
require_relative "stat_power/distributions/student_t"
require_relative "stat_power/distributions/noncentral_t"
require_relative "stat_power/distributions/f_distribution"
require_relative "stat_power/distributions/noncentral_f"
require_relative "stat_power/distributions/chi_square"
require_relative "stat_power/distributions/noncentral_chi_square"
require_relative "stat_power/solvers/bisection"
require_relative "stat_power/effect_size/conventional"
require_relative "stat_power/effect_size/proportion"
require_relative "stat_power/effect_size/chi_square"
require_relative "stat_power/normal_mean"
require_relative "stat_power/proportion"
require_relative "stat_power/t_test"
require_relative "stat_power/t_test_unequal"
require_relative "stat_power/correlation"
require_relative "stat_power/anova"
require_relative "stat_power/f2"
require_relative "stat_power/chi_square"

module StatPower
end
